name: Build and Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.16.0"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: |
          yarn docs

      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "dist"
          destination-github-username: "BastKakrolot"
          destination-repository-name: "react-headless-editor-docs"
          target-branch: master
